@base_URL = http://localhost:3000/api/auth

### 18. Auth
POST {{base_URL}}
Content-Type: application/json

{
  "email": "ylez.ozievl@gmail.com",
  //dit is password van de gebruiker
  "password": "ylez"
}

### 18. Auth no admin rights
POST {{base_URL}}
Content-Type: application/json

{
  "email": "test@gmail.com",
  //dit is password van de gebruiker
  "password": "test"
}