@base_URL = http://localhost:3000/api/members
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjJkY2RhNDVmMmZkODI0YWQxMDdiYTYiLCJ1c2VybmFtZSI6InlsZXoiLCJlbWFpbCI6InlsZXoub3ppZXZsQGdtYWlsLmNvbSIsImlhdCI6MTcxNjQ2MzM3OCwiZXhwIjoxNzE2NDY2OTc4fQ.2669Da1flHXICEwvgVzL9Nj6OpOYCIIqxAMAZcXDI-4

### 1. Get ALL Members
GET {{base_URL}}

### 2. get members by ID
GET {{base_URL}}/662dfea1e2b389cb4d0c8d20

### 3. get members by name
GET {{base_URL}}/name/tom

### 4. POST member
POST {{base_URL}}
content-type: application/json
x-auth-token: {{authToken}}

{
  "name": "Kobe9999sss",
  "lastName" :  "Bryant",
  "birthDate" : "1978-08-23",
  "gsm" : "+17181234569",
  "email" : "kobe.bryant@gmail.com",
  "membershipType" :  "all-in",
  "paid" : true
}

### 5. PUT (Edit) member
PUT {{base_URL}}/664f27ac2e88b4885109a370
Content-Type: application/json
x-auth-token: {{authToken}}

{
  "name": "ChangedToNewKobe",
  "lastName" :  "NewBryant",
  "birthDate" : "1978-08-23",
  "gsm" : "+17181234569",
  "email" : "kobe.bryant@gmail.com",
  "membershipType" :  "all-in",
  "paid" : true
}

### 6. Delete member
DELETE {{base_URL}}/664f27ac2e88b4885109a370
x-auth-token: {{authToken}}

### 7. Get all members who paid or didn't paid for membership
GET {{base_URL}}/paid=true

### 8. Set membership as paid
PATCH {{base_URL}}/setpaid/664f27ac2e88b4885109a370
x-auth-token: {{authToken}}

### 9. Get members by membership Type
GET {{base_URL}}/type/all-in

### 10. Set membership type
PATCH {{base_URL}}/setmembershiptype/664f27ac2e88b4885109a370
Content-Type: application/json
x-auth-token: {{authToken}}


{
  "membershipType" : "mma"
}