@base_URL = http://localhost:3000/api/admins
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjUwYjU2M2E4N2UyYTZhN2Y1YzhjNTYiLCJ1c2VybmFtZSI6InlsZXoiLCJlbWFpbCI6InlsZXoub3ppZXZsQGdtYWlsLmNvbSIsImlzQWRtaW4iOnRydWUsImlhdCI6MTcxNjU2NTczMCwiZXhwIjoxNzE2NTY5MzMwfQ.RRpgTbXOeoq1c4-keqoNuOV6htNPy-eL1IKe9H2RXPs

### 11. Get admins
GET {{base_URL}}

### 12. Post admin
POST {{base_URL}}
Content-Type: application/json

{
  "username": "test",
  "email":  "test@gmail.com",
  "password": "test"
}

### 13. Put admin
PUT {{base_URL}}/6650bce66372fac169149ee2
Content-Type: application/json
x-auth-token: {{authToken}}

{
  "username": "PutTest2",
  "email": "pustJustas@example.com",
  "password": "test"
}

### 14. Patch admin email
PATCH  {{base_URL}}/change-email/6650bce66372fac169149ee2
Content-Type: application/json
x-auth-token: {{authToken}}

{
  "email": "patchemail2@example.com"
}

### 15. Patch admin password
PATCH  {{base_URL}}/change-psw/6650bce66372fac169149ee2
Content-Type: application/json
x-auth-token: {{authToken}}

{
  "password": "tess"
}

### 16. Forgot email admin
GET {{base_URL}}/forgot-email/ylez
Content-Type: application/json

{
  "username": "ylez"
}

### 17. Delete admin
DELETE {{base_URL}}/delete/6650b751f433fb7739736897
x-auth-token: {{authToken}}
